config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
   resources :users, :only => [:show] do 
    resources :contents
  end

  root to: "users#show"

  get '/searches', to: "searches#index"

  get '/movie', to: "searches#movie"

end

app/models/content.rb
class Content < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

   protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
  end

  def show
    @content = Content.find(content_params)
  end

  def new
  end

  def edit
  end

  def create
  end

  def delete
  end

   private

    def content_params
      params.require(:content).permit(:title, :poster_url, :plot)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
  	if params[:q]
  	 resp = Typhoeus.get("http://omdbapi.com", :params => {:s => params[:q]})
  	 json_resp = JSON.parse(resp.body)
  	 @search = json_resp["Search"]
  	else
  	@search = []
  	end
  end

  def movie
  	if params[:q]
  	resp = Typhoeus.get("http://omdbapi.com", :params => {:i => params[:q]})
  	json_resp = JSON.parse(resp.body)
  	@movie = json_resp
  	else
  	 @movie = {}
  	 redirect_to "/searches" 
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    
  end

  def show
    if current_user
    @user = User.find(current_user)
      @content = current_user.contents
    else
      redirect_to new_user_session_path
    end
  end

  def new
  end

  def edit
  end

  def create

  end

  def delete
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/create.html.erb
<h1>Contents#create</h1>
<p>Find me in app/views/contents/create.html.erb</p>

app/views/contents/delete.html.erb
<h1>Contents#delete</h1>
<p>Find me in app/views/contents/delete.html.erb</p>

app/views/contents/edit.html.erb
<h1>Contents#edit</h1>
<p>Find me in app/views/contents/edit.html.erb</p>

app/views/contents/index.html.erb
<h1>Contents#index</h1>
<p>Find me in app/views/contents/index.html.erb</p>

app/views/contents/new.html.erb
<h1>Contents#new</h1>
<p>Find me in app/views/contents/new.html.erb</p>

app/views/contents/show.html.erb
<h1>Contents#show</h1>
<p>Find me in app/views/contents/show.html.erb</p>

<% @content.each do |x| %>

	<img src"<%= x.poster_url %>">
	<h3><%= x.title %></h3>
	<p><%= x.plot %></p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieFavsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
			<li><%= link_to "Sign in", new_user_session_path %></li>
			<li><%= link_to "Search", searches_path %></li>
			<li><%= link_to "Profile", root_path %></li>
			<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>


	</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/searches/index.html.erb
<h1>Movie Search</h1>


<%= form_tag("/searches", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>


<% @search.each do |x| %>

	<h2><%= x["Title"] %></h2>
	<a href='/movie?q=<%=x["imdbID"]%>'><p><%= x["imdbID"] %></p></a>


<% end %>

app/views/searches/movie.html.erb
<h1>Searches#movie</h1>
<p>Find me in app/views/searches/movie.html.erb</p>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>

	<img src="<%= @movie["Poster"] %>" >
	<p> <%= @movie["Plot"] %></p>

	
</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% @users.each do |x| %>

	<%= x.username %>

<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>


<%= @user.email %><br>
<%= @user.username %><br>

<% @content.each do |x| %>

	<img src="<%= x.poster_url %>">
	<h2><%= x.title %></h2>
	<p><%= x.plot %></p>
	
<% end %>